version: '2'
services:
  nginx-ldap:
    build:
      context: .
      dockerfile: ./nginx-ldap/Dockerfile
    expose:
      - "8888"
    depends_on:
      - openldap
    restart: always

  
  nginx:
    image: bitnami/nginx
    ports:
     - "8080:8080"
    volumes:
     - ./app:/app
     - ./conf/ldap_nginx.conf:/opt/bitnami/nginx/conf/server_blocks/ldap_nginx.conf
    depends_on:
      - nginx-ldap
    restart: always

  
  openldap:
    image: bitnami/openldap
    expose:
      - "1389"
      - "1636"
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=@dminpasswordisverysecure!2
      - LDAP_USERS=admin
      - LDAP_PASSWORDS=@dminpasswordisverysecure!2
    restart: always
